/* Generated By:JavaCC: Do not edit this line. clikeConstants.java */
package traductor;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface clikeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 1;
  /** RegularExpression Id. */
  int DIGIT = 2;
  /** RegularExpression Id. */
  int tBBAJA = 3;
  /** RegularExpression Id. */
  int tINIT_COMENT = 4;
  /** RegularExpression Id. */
  int tBOOL = 5;
  /** RegularExpression Id. */
  int tCHAR = 6;
  /** RegularExpression Id. */
  int tINT = 7;
  /** RegularExpression Id. */
  int tCADENA = 8;
  /** RegularExpression Id. */
  int tVOID = 9;
  /** RegularExpression Id. */
  int tRETURN = 10;
  /** RegularExpression Id. */
  int tWHILE = 11;
  /** RegularExpression Id. */
  int tIF = 12;
  /** RegularExpression Id. */
  int tELSE = 13;
  /** RegularExpression Id. */
  int tFOR = 14;
  /** RegularExpression Id. */
  int tCOMA = 15;
  /** RegularExpression Id. */
  int tPCOMA = 16;
  /** RegularExpression Id. */
  int tDIV = 17;
  /** RegularExpression Id. */
  int tSUM = 18;
  /** RegularExpression Id. */
  int tRES = 19;
  /** RegularExpression Id. */
  int tMUL = 20;
  /** RegularExpression Id. */
  int tMODULO = 21;
  /** RegularExpression Id. */
  int tIGUAL = 22;
  /** RegularExpression Id. */
  int tDIST = 23;
  /** RegularExpression Id. */
  int tEQUIVALE = 24;
  /** RegularExpression Id. */
  int tMENOR = 25;
  /** RegularExpression Id. */
  int tMAYOR = 26;
  /** RegularExpression Id. */
  int tMENOR_IG = 27;
  /** RegularExpression Id. */
  int tMAYOR_IG = 28;
  /** RegularExpression Id. */
  int tAND = 29;
  /** RegularExpression Id. */
  int tOR = 30;
  /** RegularExpression Id. */
  int tNEG = 31;
  /** RegularExpression Id. */
  int tREF = 32;
  /** RegularExpression Id. */
  int tINI_CORCH = 33;
  /** RegularExpression Id. */
  int tFIN_CORCH = 34;
  /** RegularExpression Id. */
  int tINI_PARENT = 35;
  /** RegularExpression Id. */
  int tFIN_PARENT = 36;
  /** RegularExpression Id. */
  int tINI_LLAVES = 37;
  /** RegularExpression Id. */
  int tFIN_LLAVES = 38;
  /** RegularExpression Id. */
  int tIDENT = 39;
  /** RegularExpression Id. */
  int tDIGIT_CONST = 40;
  /** RegularExpression Id. */
  int tSTRING_CONST = 41;
  /** RegularExpression Id. */
  int tCHAR_CONST = 42;
  /** RegularExpression Id. */
  int tBOOL_CONST = 43;
  /** RegularExpression Id. */
  int tERROR = 48;
  /** RegularExpression Id. */
  int tCOMENT = 49;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<LETTER>",
    "<DIGIT>",
    "\"_\"",
    "\"//\"",
    "\"bool\"",
    "\"char\"",
    "\"int\"",
    "\"string\"",
    "\"void\"",
    "\"return\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\",\"",
    "\";\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"%\"",
    "\"=\"",
    "\"!=\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"&\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<tIDENT>",
    "<tDIGIT_CONST>",
    "<tSTRING_CONST>",
    "<tCHAR_CONST>",
    "<tBOOL_CONST>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<tERROR>",
    "<tCOMENT>",
  };

}
